/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MCIMX7U5xxxxx
package_id: MCIMX7U5CVP05
mcu_data: ksdk2_0
processor_version: 7.0.1
board: MCIMX7ULP-EVK-REV-B
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_gpio_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AG16, peripheral: PTA, signal: 'port, 12', pin_signal: PTA12, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AF16, peripheral: PTA, signal: 'port, 13', pin_signal: PTA13, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: AF17, peripheral: PTA, signal: 'port, 14', pin_signal: PTA14, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AF18, peripheral: PTA, signal: 'port, 15', pin_signal: PTA15, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AB20, peripheral: PTA, signal: 'port, 21', pin_signal: PTA21, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AD20, peripheral: PTA, signal: 'port, 23', pin_signal: PTA23, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: AF20, peripheral: PTA, signal: 'port, 24', pin_signal: PTA24, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AG20, peripheral: PTA, signal: 'port, 25', pin_signal: PTA25, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AF14, peripheral: PTA, signal: 'port, 3', pin_signal: PTA3, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AF24, peripheral: PTA, signal: 'port, 31', pin_signal: PTA31, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: AF5, peripheral: PTB, signal: 'port, 6', pin_signal: PTB6, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AF6, peripheral: PTB, signal: 'port, 7', pin_signal: PTB7, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: AD7, peripheral: PTB, signal: 'port, 9', pin_signal: PTB9, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: AB7, peripheral: PTB, signal: 'port, 11', pin_signal: PTB11, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: D18, peripheral: PTC, signal: 'port, 0', pin_signal: PTC0, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: B15, peripheral: PTC, signal: 'port, 10', pin_signal: PTC10, direction: INPUT, IBE: IBE_1_Enabled, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: B14, peripheral: PTC, signal: 'port, 11', pin_signal: PTC11, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: A14, peripheral: PTC, signal: 'port, 12', pin_signal: PTC12, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: E13, peripheral: PTC, signal: 'port, 14', pin_signal: PTC14, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: F13, peripheral: PTC, signal: 'port, 15', pin_signal: PTC15, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: G12, peripheral: PTC, signal: 'port, 17', pin_signal: PTC17, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: F12, peripheral: PTC, signal: 'port, 18', pin_signal: PTC18, direction: INPUT, IBE: IBE_1_Enabled, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: E12, peripheral: PTC, signal: 'port, 19', pin_signal: PTC19, direction: OUTPUT, OBE: OBE_1_Enabled, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: B8, peripheral: PTE, signal: 'port, 12', pin_signal: PTE12, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: D2, peripheral: PTF, signal: 'port, 0', pin_signal: PTF0, direction: INPUT, IBE: IBE_1_Enabled}
  - {pin_num: B2, peripheral: PTF, signal: 'port, 1', pin_signal: PTF1, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: G5, peripheral: PTF, signal: 'port, 10', pin_signal: PTF10, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: G6, peripheral: PTF, signal: 'port, 11', pin_signal: PTF11, direction: OUTPUT, OBE: OBE_1_Enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_gpio_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_gpio_pins(void) {                                /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_GPIO_PINS_BATT_ADC_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_BATT_ADC_EN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_VOL_DOWN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_VOL_DOWN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_WL_REG_ON_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_WL_REG_ON_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_BT_REG_ON_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_BT_REG_ON_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_M4_PER_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_M4_PER_EN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_AUD_INT_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_AUD_INT_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_AUD_PWR_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_AUD_PWR_EN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_A7_POW_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_A7_POW_EN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_VOL_UP_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_VOL_UP_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_WL_HOST_WAKE_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_WL_HOST_WAKE_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PMIC_INT_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PMIC_INT_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_DDR_SW_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_DDR_SW_EN_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_BT_HOST_WAKE_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_BT_HOST_WAKE_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_SEN_INT_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_SEN_INT_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_USB_OTG_PWR_EN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_USB_OTG_PWR_EN_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_SD0_CD_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_SD0_CD_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_USB_CC_SEL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_USB_CC_SEL_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_USB_INT_B_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_USB_INT_B_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PTC14_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PTC14_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PTC15_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PTC15_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PTC17_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PTC17_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_DSI_HDMI_INT_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_DSI_HDMI_INT_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_MIPI_RESET_B_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_MIPI_RESET_B_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_BT_DEV_WAKE_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_BT_DEV_WAKE_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_TOUCH_INT_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_TOUCH_INT_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_TOUCH_RST_B_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_TOUCH_RST_B_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PTF10_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PTF10_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(INIT_GPIO_PINS_PTF11_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_GPIO_PINS_PTF11_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_OBE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_i2s_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AG14, peripheral: I2S0, signal: 'i2s_rxd, 0', pin_signal: PTA2, DSE: DSE_1_Hi_Drive}
  - {pin_num: AD15, peripheral: I2S0, signal: i2s_mclk, pin_signal: PTA4, DSE: DSE_1_Hi_Drive}
  - {pin_num: AC15, peripheral: I2S0, signal: i2s_tx_bclk, pin_signal: PTA5, DSE: DSE_1_Hi_Drive}
  - {pin_num: AB15, peripheral: I2S0, signal: i2s_tx_fs, pin_signal: PTA6, DSE: DSE_1_Hi_Drive}
  - {pin_num: AD14, peripheral: I2S0, signal: 'i2s_txd, 0', pin_signal: PTA7, DSE: DSE_1_Hi_Drive}
  - {pin_num: AF2, peripheral: I2S1, signal: i2s_tx_bclk, pin_signal: PTB1, DSE: DSE_1_Hi_Drive}
  - {pin_num: AE3, peripheral: I2S1, signal: i2s_tx_fs, pin_signal: PTB2, DSE: DSE_1_Hi_Drive}
  - {pin_num: AE4, peripheral: I2S1, signal: 'i2s_txd, 0', pin_signal: PTB3, DSE: DSE_1_Hi_Drive}
  - {pin_num: AC7, peripheral: I2S1, signal: 'i2s_rxd, 0', pin_signal: PTB10, DSE: DSE_1_Hi_Drive}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_i2s_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_i2s_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S0_RXD0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S0_RXD0_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S0_MCLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S0_MCLK_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S0_TX_BCLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S0_TX_BCLK_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S0_TX_FS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S0_TX_FS_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S0_TXD0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S0_TXD0_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S1_TX_BCLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S1_TX_BCLK_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S1_RXD0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S1_RXD0_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S1_TX_FS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S1_TX_FS_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(INIT_I2S_PINS_I2S1_TXD0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2S_PINS_I2S1_TXD0_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_uart_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AB16, peripheral: LPUART2, signal: lpuart_cts_b, pin_signal: PTA8, identifier: UART2_CTS, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AC16, peripheral: LPUART2, signal: lpuart_rts_b, pin_signal: PTA9, identifier: UART2_RTS, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AD16, peripheral: LPUART2, signal: lpuart_tx, pin_signal: PTA10, identifier: UART2_TX, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AD18, peripheral: LPUART2, signal: lpuart_rx, pin_signal: PTA11, identifier: UART2_RX, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AC19, peripheral: LPUART0, signal: lpuart_tx, pin_signal: PTA18, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AB19, peripheral: LPUART0, signal: lpuart_rx, pin_signal: PTA19, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: F17, peripheral: LPUART4, signal: lpuart_tx, pin_signal: PTC2, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: G17, peripheral: LPUART4, signal: lpuart_rx, pin_signal: PTC3, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: F9, peripheral: LPUART6, signal: lpuart_cts_b, pin_signal: PTE8, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: G9, peripheral: LPUART6, signal: lpuart_rts_b, pin_signal: PTE9, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: D8, peripheral: LPUART6, signal: lpuart_tx, pin_signal: PTE10, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: A8, peripheral: LPUART6, signal: lpuart_rx, pin_signal: PTE11, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_uart_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_uart_pins(void) {                                /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_UART_PINS_UART2_TX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART2_TX_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART2_RX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART2_RX_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART0_TX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART0_TX_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART0_RX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART0_RX_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART2_CTS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART2_CTS_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART2_RTS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART2_RTS_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART4_TX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART4_TX_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART4_RX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART4_RX_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART6_TX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART6_TX_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART6_RX_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART6_RX_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART6_CTS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART6_CTS_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_UART_PINS_UART6_RTS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_UART_PINS_UART6_RTS_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC1_SW_MUX_CTL_PAD_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_i2c_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AG18, peripheral: LPI2C0, signal: lpi2c_scl, pin_signal: PTA16, ODE: ODE_1_Open_drain}
  - {pin_num: AD19, peripheral: LPI2C0, signal: lpi2c_sda, pin_signal: PTA17, ODE: ODE_1_Open_drain}
  - {pin_num: AC8, peripheral: LPI2C3, signal: lpi2c_scl, pin_signal: PTB12, ODE: ODE_1_Open_drain}
  - {pin_num: AD8, peripheral: LPI2C3, signal: lpi2c_sda, pin_signal: PTB13, ODE: ODE_1_Open_drain}
  - {pin_num: F16, peripheral: LPI2C5, signal: lpi2c_scl, pin_signal: PTC4, ODE: ODE_1_Open_drain}
  - {pin_num: D17, peripheral: LPI2C5, signal: lpi2c_sda, pin_signal: PTC5, ODE: ODE_1_Open_drain}
  - {pin_num: H7, peripheral: LPI2C7, signal: lpi2c_scl, pin_signal: PTF12, ODE: ODE_1_Open_drain}
  - {pin_num: H6, peripheral: LPI2C7, signal: lpi2c_sda, pin_signal: PTF13, ODE: ODE_1_Open_drain}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_i2c_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_i2c_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C0_SCL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C0_SCL_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C0_SDA_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C0_SDA_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C3_SCL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C3_SCL_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C3_SDA_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C3_SDA_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C5_SCL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C5_SCL_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C5_SDA_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C5_SDA_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C7_SCL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C7_SCL_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(INIT_I2C_PINS_I2C7_SDA_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_I2C_PINS_I2C7_SDA_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_ODE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_adc_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AD22, peripheral: ADC0, signal: adc_ch10a, pin_signal: PTA20}
  - {pin_num: AB16, peripheral: ADC1, signal: adc_ch5a, pin_signal: PTA8, identifier: ADC1_CH5A}
  - {pin_num: AC16, peripheral: ADC1, signal: adc_ch5b, pin_signal: PTA9, identifier: ADC1_CH5B}
  - {pin_num: AD16, peripheral: ADC1, signal: adc_ch6a, pin_signal: PTA10, identifier: ADC1_CH6A}
  - {pin_num: AD18, peripheral: ADC1, signal: adc_ch6b, pin_signal: PTA11, identifier: ADC1_CH6B}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_adc_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_adc_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_ADC_PINS_ADC1_CH6A_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_ADC_PINS_ADC1_CH6B_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_ADC_PINS_BATT_ADC_IN_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_ADC_PINS_ADC1_CH5A_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_ADC_PINS_ADC1_CH5B_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_ewm_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AC20, peripheral: EWM, signal: ewm_out_b, pin_signal: PTA22}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_ewm_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_ewm_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_EWM_PINS_EWM_OUT_B_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_sjc_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AF21, peripheral: JTAG, signal: jtag_tms, pin_signal: PTA26, identifier: JTAG_TMS}
  - {pin_num: AF22, peripheral: JTAG, signal: jtag_tdo, pin_signal: PTA27}
  - {pin_num: AG22, peripheral: JTAG, signal: jtag_tdi, pin_signal: PTA28}
  - {pin_num: AD23, peripheral: JTAG, signal: jtag_tclk, pin_signal: PTA29, identifier: JTAG_TCLK}
  - {pin_num: AD24, peripheral: JTAG, signal: jtag_trst_b, pin_signal: PTA30}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_sjc_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_sjc_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_SJC_PINS_JTAG_TMS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SJC_PINS_JTAG_TMS_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_SJC_PINS_JTAG_TDO_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SJC_PINS_JTAG_TDI_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SJC_PINS_JTAG_TDI_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(INIT_SJC_PINS_JTAG_TCLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SJC_PINS_JTAG_TCLK_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(INIT_SJC_PINS_JTAG_TRST_B_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SJC_PINS_JTAG_TRST_B_PIN_FUNCTION_ID,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_qspi_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AG6, peripheral: QSPIA, signal: 'qspia_ss_b, 0', pin_signal: PTB8}
  - {pin_num: AF8, peripheral: QSPIA, signal: qspia_sclk, pin_signal: PTB15}
  - {pin_num: AF9, peripheral: QSPIA, signal: 'qspia_data, 3', pin_signal: PTB16}
  - {pin_num: AF10, peripheral: QSPIA, signal: 'qspia_data, 2', pin_signal: PTB17}
  - {pin_num: AG10, peripheral: QSPIA, signal: 'qspia_data, 1', pin_signal: PTB18}
  - {pin_num: AD10, peripheral: QSPIA, signal: 'qspia_data, 0', pin_signal: PTB19}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_qspi_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_qspi_pins(void) {                                /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_SCLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_DATA3_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_DATA2_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_DATA1_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_DATA0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_QSPI_PINS_QSPIA_SS0_B_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_rtc_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: AG8, peripheral: RTC, signal: rtc_clkout, pin_signal: PTB14}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_rtc_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_rtc_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_RTC_PINS_RTC_CLK_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_usb_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: D13, peripheral: USB0, signal: usb0_id, pin_signal: PTC13}
  - {pin_num: G13, peripheral: USB1, signal: 'usb1_oc, 2', pin_signal: PTC16}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_usb_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_usb_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_USB_PINS_USB_OTG_ID_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_USB_PINS_USB_OTG_OC_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_sdhc_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: A24, peripheral: SDHC0, signal: sdhc_reset_b, pin_signal: PTD0}
  - {pin_num: B24, peripheral: SDHC0, signal: sdhc_cmd, pin_signal: PTD1}
  - {pin_num: B23, peripheral: SDHC0, signal: sdhc_clk, pin_signal: PTD2, IBE: IBE_1_Enabled}
  - {pin_num: B22, peripheral: SDHC0, signal: 'sdhc_d, 7', pin_signal: PTD3}
  - {pin_num: A22, peripheral: SDHC0, signal: 'sdhc_d, 6', pin_signal: PTD4}
  - {pin_num: D21, peripheral: SDHC0, signal: 'sdhc_d, 5', pin_signal: PTD5}
  - {pin_num: D22, peripheral: SDHC0, signal: 'sdhc_d, 4', pin_signal: PTD6}
  - {pin_num: A20, peripheral: SDHC0, signal: 'sdhc_d, 3', pin_signal: PTD7}
  - {pin_num: B20, peripheral: SDHC0, signal: 'sdhc_d, 2', pin_signal: PTD8}
  - {pin_num: B19, peripheral: SDHC0, signal: 'sdhc_d, 1', pin_signal: PTD9}
  - {pin_num: B18, peripheral: SDHC0, signal: 'sdhc_d, 0', pin_signal: PTD10}
  - {pin_num: A18, peripheral: SDHC0, signal: sdhc_dqs, pin_signal: PTD11}
  - {pin_num: D12, peripheral: SDHC1, signal: 'sdhc_d, 1', pin_signal: PTE0}
  - {pin_num: A12, peripheral: SDHC1, signal: 'sdhc_d, 0', pin_signal: PTE1}
  - {pin_num: B12, peripheral: SDHC1, signal: sdhc_clk, pin_signal: PTE2, IBE: IBE_1_Enabled}
  - {pin_num: B11, peripheral: SDHC1, signal: sdhc_cmd, pin_signal: PTE3}
  - {pin_num: B10, peripheral: SDHC1, signal: 'sdhc_d, 3', pin_signal: PTE4}
  - {pin_num: A10, peripheral: SDHC1, signal: 'sdhc_d, 2', pin_signal: PTE5}
  - {pin_num: B6, peripheral: SDHC1, signal: sdhc_vs, pin_signal: PTE14}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_sdhc_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_sdhc_pins(void) {                                /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_nRST_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_CMD_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DQS_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_CLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SDHC_PINS_SD0_CLK_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA7_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA6_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA5_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA4_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA3_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA2_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD0_DATA1_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_DATA1_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_DATA0_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_SD1_VSEL_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_CLK_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinConfig(INIT_SDHC_PINS_WL_SD1_CLK_PIN_FUNCTION_ID,
                        IOMUXC1_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_CMD_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_DATA3_PIN_FUNCTION_ID, 0U);
    IOMUXC_SetPinMux(INIT_SDHC_PINS_WL_SD1_DATA2_PIN_FUNCTION_ID, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
init_tpm_pins:
- options: {callFromInitBoot: 'false', coreID: cm4}
- pin_list:
  - {pin_num: B3, peripheral: TPM4, signal: 'tpm_ch, 1', pin_signal: PTF2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : init_tpm_pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void init_tpm_pins(void) {                                 /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(INIT_TPM_PINS_LED_PWM_EN_PIN_FUNCTION_ID, 0U);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
